# Домашнее задание «Библиотека numpy. Вычислительные задачи»

In [ ]:
import numpy as np

# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [ ]:
n = int(input())

5


In [ ]:
my_array = np.array([i for i in range(n-1,-1,-1)])
my_array

array([4, 3, 2, 1, 0])

In [ ]:
# или с помощью arange
my_array = np.arange(n-1,-1,-1)
my_array

array([4, 3, 2, 1, 0])

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [ ]:
my_matrix = np.diag(np.arange(n, 0, -1))
my_matrix

array([[5, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
my_matrix.sum() #здесь складываем все элементы, хотя нужно только диагональные. Но у нас остальные нули, так что можно


15

In [ ]:
sum(np.diagonal(my_matrix)) # можно и так, здесь конкретно диагональные элементы складываем

15

In [ ]:
# или с помощью np.linspace, т.к согласно условию нет ограничений 
# на элементы матрицы, кроме как на то, что диагонльные в диапазоне от n до 0
my_matrix = np.linspace(n, 0, n**2).reshape(n,n)
my_matrix

array([[5.        , 4.79166667, 4.58333333, 4.375     , 4.16666667],
       [3.95833333, 3.75      , 3.54166667, 3.33333333, 3.125     ],
       [2.91666667, 2.70833333, 2.5       , 2.29166667, 2.08333333],
       [1.875     , 1.66666667, 1.45833333, 1.25      , 1.04166667],
       [0.83333333, 0.625     , 0.41666667, 0.20833333, 0.        ]])

In [ ]:
sum(np.diagonal(my_matrix)) # а здесь только так, т.к недиагональные - не нулевые

12.5

# Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [ ]:
from numpy import linalg # библиотека для задач линейной алгебры

In [ ]:
a = np.array([[4, 2, 1],[4,3,0], [0, 5, 4]]) # коэффициенты при переменных
b = np.array([4, 12,-3]) # вободные члены

In [ ]:
linalg.solve(a, b) # находим x,y,z

array([ 0.58333333,  3.22222222, -4.77777778])

In [ ]:
np.allclose(np.dot(a, linalg.solve(a,b)), b) # проверка решения

True

# Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [ ]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [ ]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [ ]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [ ]:
dim = users_stats.shape # определяем размеры исходной матрицы
result = 0 # исходный косинус угла
user = np.zeros(dim[1]) # инициализируем user массивом размера dim[1] и заполняем 0

for _ in range(dim[0]): # поочередно проверяем всех пользователей на косинусное сходство
    if cosine(users_stats[_,:],next_user_stats) > result:
        result = cosine(users_stats[_,:],next_user_stats)
        user = users_stats[_,:]
        
print(f'Самый похожий пользователь : {user}, косинусное сходство : {result}')

Самый похожий пользователь : [0 1 1 0 0 0], косинусное сходство : 0.9486832980505138


In [ ]:
# Более короткое решение с использованием lambda, map, list comprehension и возможностей numpy argmax

result = np.array(list(map(lambda i: cosine(users_stats[i,:],next_user_stats),[i for i in range(dim[0])])))
# перебираем i в интервале от нуля до размера исходной матрицы. В соответствие каждому i с помощью lambda ставится значение функции 
index = np.argmax(result)
print(f'Самый похожий пользователь : {users_stats[index,:]},  косинусное сходство : {result[index]}')

Самый похожий пользователь : [0 1 1 0 0 0],  косинусное сходство : 0.9486832980505138
